config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

    root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'
    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    get 'tags/:tag',  to: 'static_pages#home',as: :tag
    get 'cordinates/name', to: 'cordinates#name'
    post 'cordinates/name', to: 'cordinates#name'
    resources :users
    resources :microposts,          only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cordinate.rb
class Cordinate < ApplicationRecord
  belongs_to :user
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    acts_as_taggable_on :categories,:colors,:patterns
    #acts_as_taggable            # acts_as_taggable_on :tags のエイリアス
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 140 }
  validate  :picture_size
  
  private
  
  # アップロードされた画像のサイズをバリデーションする
  def picture_size
      if picture.size > 5.megabytes
          errors.add(:picture, "should be less than 5MB")
      end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :name, presence: true,length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true,length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    # 試作feedの定義
    # 完全な実装は次章の「ユーザーをフォローする」を参照
    def feed
        Micropost.where("user_id = ?", id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  
  # ユーザーのログインを確認する
  def logged_in_user
      unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
      end
  end
end

app/controllers/cordinates_controller.rb
class CordinatesController < ApplicationController
  def name
      @cordinate = Cordinate.new(item1: params["item1"])
      @feed_items = current_user.feed.paginate(page: params[:page])
      @cordinate.save
  end
  
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user,   only: :destroy
    
    def create
        @micropost = current_user.microposts.build(micropost_params)
        if @micropost.save
            flash[:success] = "Micropost created!"
            redirect_to root_url
            else
            @feed_items = []
            render 'static_pages/home'
        end
    end
    
    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer || root_url
    end
    
    private
    
    def micropost_params
        params.require(:micropost).permit(:title,:picture,:category_list,:color_list,:pattern_list)
    end
    
    def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
          log_in user
          redirect_to user
          # ユーザーログイン後にユーザー情報のページにリダイレクトする
          else
          # エラーメッセージを作成する
          flash.now[:danger] = 'Invalid email/password combination' # 本当は正しくない
          render 'new'
      end
  end
  
  def destroy
      log_out
      redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
      #if logged_in?
      #   @micropost  = current_user.microposts.build
      #   @feed_items = current_user.feed.paginate(page: params[:page])
      #end
      if logged_in?
          @micropost  = current_user.microposts.build
          if params[:tag]
              @feed_items = Micropost.tagged_with(params[:tag]).paginate(page: params[:page])
          else
              @feed_items = current_user.feed.paginate(page: params[:page])
          end
      end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
    def show
        @user = User.find(params[:id])
        @microposts = @user.microposts.paginate(page: params[:page])
    end
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            flash[:success] = "Welcome to the Sample App!"
            redirect_to @user
        else
            render 'new'
        end
    end
    
    private
    
    def user_params
        params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation)
    end
    
    def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
    end
    
    # 管理者かどうかを確認
    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # ページごとの完全なタイトルを返します。
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
            else
            page_title + " | " + base_title
        end
    end
end

app/helpers/cordinates_helper.rb
module CordinatesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user?(user)
        user == current_user
    end
    
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
            elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(:remember, cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end
    def logged_in?
        !current_user.nil?
    end
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
    
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    
    # アクセスしようとしたURLを覚えておく
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    # 引数で与えられたユーザーのGravatar画像を返す
    def gravatar_for(user, size: 80)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/cordinates/name.html.erb
<h1>Cordinates#name</h1>
<p>Find me in app/views/cordinates/name.html.erb</p>
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>
<%= form_for(cordinates_name_url) do |f| %>
  <div class="field">
    <%= f.label :item1, "カテゴリ" %><br>
	<%= f.select :item1,  [["17", "17"]] %>
  </div>
   <%= f.submit "Post", class: "btn btn-primary" %>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "CLOSET", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", "" %></li>
          <li class="dropdown">
            <a href="" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", "" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= render 'layouts/shim' %>
  </head>

  <body>
     <%= render 'layouts/header' %>
	<div class="container">
	　　<% flash.each do |message_type, message| %>
        　<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      　<% end %>
 　　　　<%= yield %>
	　　<%= render 'layouts/footer' %>
	　　<%= debug(params) if Rails.env.development? %>
	</div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="title">
  	<%= micropost.title %>
	  <%= micropost.id %>
	<%= image_tag micropost.picture.url if micropost.picture? %>
	<div id="tag">
	  <%= render 'microposts/microposts_tag_list', tag_list: micropost.category_list ,class:"tag"%>
	  <%= render 'microposts/microposts_tag_list', tag_list: micropost.color_list ,class:"tag"%>
	  <%= render 'microposts/microposts_tag_list', tag_list: micropost.pattern_list,class:"tag" %>
	</div>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
	<% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/microposts/_microposts_tag_list.html.erb
<% tag_list.each do |tag| %>
  <!--<span class="label label-primary"><%= tag %></span>-->
  <span class="label label-primary"><%= link_to tag, tag_path(tag) %></span>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :title, placeholder: "Compose new micropost..." %>
  </div>
  <div class="field">
    <%= f.label :category_list, "カテゴリ" %><br>
	<!--<%= text_field_tag 'micropost[category_list]', @micropost.category_list.join(',') %>-->
	<%= f.select :category_list, [["トップス", "トップス"], ["ボトムス", "ボトムス"], ["アウター", "アウター"], 
									["ワンピース", "ワンピース"], ["タイツ・ストッキング", "タイツ・ストッキング"], ["ソックス", "ソックス"],
									["シューズ", "シューズ"], ["アクセサリー", "アクセサリー"], ["その他", "その他"]] %>
  </div>
  <div class="field">
    <%= f.label :color_list, "カラー" %><br>
    <%= f.select :color_list, [["ホワイト", "ホワイト"], ["ブラック", "ブラック"], ["グレー", "グレー"], 
									["ブラウン", "ブラウン"], ["レッド", "レッド"], ["オレンジ", "オレンジ"], 
									["イエロー", "イエロー"], ["グリーン", "グリーン"], ["ブルー", "ブルー"],
									["パープル", "パープル"], ["ピンク", "ピンク"], ["その他", "その他"]] %>
  </div>
  <div class="field">
    <%= f.label :pattern_list, "パターン" %><br>
    <%= f.select :pattern_list, [["無地", "無地"], ["ドット", "ドット"], ["花柄", "花柄"], 
									["ボーダー", "ボーダー"], ["ストライプ", "ストライプ"], ["チェック", "チェック"], 
									["アニマル", "アニマル"], ["和柄", "和柄"], ["レース", "レース"],["その他", "その他"]] %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/#screencast">screencast</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
	<div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>CLOSET</h1>

  <h2>
    服とコーデを簡単管理
  </h2>

  <%= link_to "Sign up now!", 'signup', class: "btn btn-lg btn-primary" %>
</div>

<!--<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>-->
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
	<section class="user-info">
	<h1><%= gravatar_for @user %>
	    <%= @user.name %>
	</h1>
	</section>
	</aside>
	<div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>